import type { RawRow } from "./excel.js";

/** Sample Asset Visits-shaped rows covering each Access Type + auto-route. */
export const DEMO_VISIT_ROWS: RawRow[] = [
  {
    ID: 946,
    UPRN: "635708",
    "Combined Address": "Flat 21, Kynaston House, Challice Way, SW2 3ER",
    "Visit Type": "RdSAP",
    "Data Source": "Vision Mobile",
    "Survey Date": "2026-09-18",
    "Next Survey": "",
    "Access Type": "No Answer",
    "Created By": "Peter May",
    "Created On": "2026-09-18",
    "Survey Design": "Dwelling",
    Number: "Flat 21",
    Block: "Kynaston House",
    "Address Line 1": "Challice Way",
    "Address Line 5": "London",
    "Post Code": "SW2 3ER",
    Archetype: "Flat",
  },
  {
    ID: 951,
    UPRN: "635765",
    "Combined Address": "11, Tillman House, Challice Way, SW2 3RA",
    "Visit Type": "RdSAP",
    "Data Source": "Vision Mobile",
    "Survey Date": "2026-09-18",
    "Access Type": "Failed appointment",
    "Created By": "Alex Surveyor",
    "Created On": "2026-09-18",
    "Survey Design": "Dwelling",
    Number: "11",
    Block: "Tillman House",
    "Address Line 1": "Challice Way",
    "Address Line 5": "London",
    "Post Code": "SW2 3RA",
    Archetype: "Flat",
  },
  {
    ID: 962,
    UPRN: "635900",
    "Combined Address": "8, Harbour Court, Quay Street, EX23 8JZ",
    "Visit Type": "SCS",
    "Data Source": "Vision Mobile",
    "Survey Date": "2026-09-18",
    "Access Type": "Refused Access",
    "Created By": "Peter May",
    "Created On": "2026-09-18",
    "Survey Design": "Dwelling",
    Number: "8",
    Block: "Harbour Court",
    "Address Line 1": "Quay Street",
    "Address Line 5": "Bude",
    "Post Code": "EX23 8JZ",
    Archetype: "House",
  },
  {
    ID: 963,
    UPRN: "635901",
    "Combined Address": "9, Harbour Court, Quay Street, EX23 8JZ",
    "Visit Type": "SCS",
    "Data Source": "Vision Mobile",
    "Survey Date": "2026-09-18",
    "Access Type": "Not Convenient",
    "Created By": "Alex Surveyor",
    "Created On": "2026-09-18",
    "Survey Design": "Dwelling",
    Number: "9",
    Block: "Harbour Court",
    "Address Line 1": "Quay Street",
    "Address Line 5": "Bude",
    "Post Code": "EX23 8JZ",
    Archetype: "House",
  },
  {
    ID: 960,
    UPRN: "635742",
    "Combined Address": "51a, Roupell Road, SW2 3EP",
    "Visit Type": "SCS",
    "Data Source": "Vision Mobile",
    "Survey Date": "2026-09-18",
    "Access Type": "Void",
    "Created By": "Alex Surveyor",
    "Created On": "2026-09-18",
    "Survey Design": "Dwelling",
    Number: "51a",
    Block: "",
    "Address Line 1": "Roupell Road",
    "Address Line 5": "London",
    "Post Code": "SW2 3EP",
    Archetype: "Flat",
  },
  {
    ID: 949,
    UPRN: "635770",
    "Combined Address": "16, Tillman House, Challice Way, SW2 3RA",
    "Visit Type": "SCS",
    "Data Source": "Vision Mobile",
    "Survey Date": "2026-09-18",
    "Access Type": "Successful",
    "Created By": "Peter May",
    "Created On": "2026-09-18",
    "Survey Design": "Dwelling",
    Number: "16",
    Block: "Tillman House",
    "Address Line 1": "Challice Way",
    "Address Line 5": "London",
    "Post Code": "SW2 3RA",
    Archetype: "Flat",
  },
  {
    ID: 970,
    UPRN: "BLK-2001",
    "Combined Address": "Harbour Court, Quay Street, EX23 8JZ",
    "Visit Type": "Block",
    "Data Source": "Vision Mobile",
    "Survey Date": "2026-09-18",
    "Access Type": "Successful",
    "Created By": "Alex Surveyor",
    "Created On": "2026-09-18",
    "Survey Design": "MTVH Blocks",
    Number: "1",
    Block: "Harbour Court",
    "Address Line 1": "Quay Street",
    "Address Line 5": "Bude",
    "Post Code": "EX23 8JZ",
    Archetype: "Low-rise block",
  },
  {
    ID: 971,
    UPRN: "GAR-601",
    "Combined Address": "G18, Harbour Court, Quay Street, EX23 8JZ",
    "Visit Type": "Garage",
    "Data Source": "Vision Mobile",
    "Survey Date": "2026-09-18",
    "Access Type": "No Answer",
    "Created By": "Peter May",
    "Created On": "2026-09-18",
    "Survey Design": "Garage Sites",
    Number: "G18",
    Block: "Harbour Court",
    "Address Line 1": "Quay Street",
    "Address Line 5": "Bude",
    "Post Code": "EX23 8JZ",
    Archetype: "Garage",
  },
];
